/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg311taskmanager;

/**
 *
 * @author Luke
 */
public class LoginUIv2 extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuUIv2
     */
    
    private NavigationCntl parentNavCntl = null;

    private LoginCntl parentLoginCntl = null;
    
    public LoginUIv2() {
        initComponents();
    }
    String userName = "";
    
    public LoginUIv2(LoginCntl newParentLoginCntl) {
        parentLoginCntl = newParentLoginCntl;
        initComponents();
    }
    public LoginUIv2(NavigationCntl newParentNavCntl, LoginCntl newParentLoginCntl) {
        parentNavCntl = newParentNavCntl;
        parentLoginCntl = newParentLoginCntl;
        //initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transparent_text_effect (1).png"))); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(10, 20, 470, 103);

        closeButton.setBackground(new java.awt.Color(153, 153, 153));
        closeButton.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton);
        closeButton.setBounds(10, 260, 60, 21);

        passwordLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        passwordLabel.setToolTipText("");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(80, 180, 90, 20);

        userNameLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("UserName:");
        userNameLabel.setToolTipText("");
        jPanel1.add(userNameLabel);
        userNameLabel.setBounds(80, 150, 110, 20);

        userNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userNameField.setToolTipText("");
        jPanel1.add(userNameField);
        userNameField.setBounds(190, 150, 140, 21);
        jPanel1.add(passwordField);
        passwordField.setBounds(190, 180, 140, 22);

        submitButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setToolTipText("");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(190, 210, 79, 25);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 490, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //String username = "";
        userName = userNameField.getText();
            char[] password = passwordField.getPassword();
            boolean authenticated = LoginUIv2.this.parentLoginCntl.requestAuthenticate(userName, password);
        
            if(authenticated){
                 System.out.println("Authenticated");
                LoginUIv2.this.parentLoginCntl.requestNavigationCntl();
            }else{
                System.out.println("NOT Authenticated");
            }
            
    }//GEN-LAST:event_submitButtonActionPerformed
    
    public String getUsername(){
        return userName;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUIv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUIv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUIv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUIv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUIv2().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
