/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg311taskmanager;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Luke
 */
public class TaskUI extends javax.swing.JFrame {

    /**
     * Creates new form TaskUI
     */
    
    private TaskCntl parentTaskCntl = null;
    
    
    
    
    public TaskUI(TaskCntl newParentTaskCntl) {
        parentTaskCntl = newParentTaskCntl;
        initComponents();
    }
  
    public TaskUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BackGround = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TaskLogo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        recreationButton = new javax.swing.JRadioButton();
        workButton = new javax.swing.JRadioButton();
        schoolButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        familyButton = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        TaskLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tasks_.png"))); // NOI18N
        jPanel1.add(TaskLogo);
        TaskLogo.setBounds(80, 400, 210, 65);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task Bigger (2).png"))); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(190, 40, 790, 230);

        buttonGroup1.add(recreationButton);
        recreationButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        recreationButton.setText("Recreation");
        jPanel1.add(recreationButton);
        recreationButton.setBounds(930, 450, 110, 25);

        buttonGroup1.add(workButton);
        workButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        workButton.setText("Work");
        jPanel1.add(workButton);
        workButton.setBounds(930, 370, 110, 25);

        buttonGroup1.add(schoolButton);
        schoolButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        schoolButton.setText("School");
        jPanel1.add(schoolButton);
        schoolButton.setBounds(930, 490, 110, 25);

        buttonGroup1.add(otherButton);
        otherButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        otherButton.setText("Other");
        jPanel1.add(otherButton);
        otherButton.setBounds(930, 530, 110, 25);

        buttonGroup1.add(familyButton);
        familyButton.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        familyButton.setText("Family");
        jPanel1.add(familyButton);
        familyButton.setBounds(930, 410, 110, 25);

        jComboBox1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(20);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Task 1", "Task 2", "Task 3", "Task 4" }));
        jComboBox1.setAutoscrolls(true);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 430, 490, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("This is where task information will go.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 540, 640, 180);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton1.setText("Edit Task");
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 770, 190, 25);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton2.setText("Delete Task");
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 770, 190, 25);

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton3.setText("Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 540, 110, 25);

        jButton4.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton4.setText("Add Task");
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 770, 190, 25);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notifications:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(880, 690, 220, 30);

        jTextPane1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jTextPane1.setText("High");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(880, 640, 180, 30);

        jToggleButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jToggleButton1.setText("On");
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(930, 740, 67, 50);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Priority Level:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(880, 590, 220, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N
        jButton5.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N
        jButton5.setEnabled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy Task BG.jpg"))); // NOI18N
        jButton5.setRolloverEnabled(false);
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 0, 1140, 900);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 960);
        jPanel1.getAccessibleContext().setAccessibleName("");

        setBounds(0, 0, 1151, 941);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        TaskUI.this.parentTaskCntl.requestNavigationCntl();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskUI().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackGround;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TaskLogo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton familyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.JRadioButton recreationButton;
    private javax.swing.JRadioButton schoolButton;
    private javax.swing.JRadioButton workButton;
    // End of variables declaration//GEN-END:variables
}
